### ISSUE TITLE
Color issues with some pictures

### ISSUE THREAD

**Issue by Darker** [chrdavis/PIFShellExtensions#1]
I am seeing incorrect colors in some of the previews. Looks like maybe the channels were switched? I can see that both those pictures are correct in GIMP, yet in windows I observe this:

![obrazek](https://user-images.githubusercontent.com/5508988/66649295-149d1380-ec2e-11e9-906a-9d55cfb95d42.png)

The one on the right is correct. All the pictures are generated by the same code. 

Here are the original images:
[debug_images.zip](https://github.com/chrdavis/PIFShellExtensions/files/3717402/debug_images.zip)

**Comment by chrdavis** [comment]
Thanks for calling this out and providing test images.  I'll look into it as soon as I can.

**Comment by chrdavis** [comment]
Fixed in latest release

https://github.com/chrdavis/PIFShellExtensions/releases/tag/v.0.7

**Comment by Darker** [comment]
Awesome, that was fast! Thanks a lot!
